server:
  port: 8080
  
spring:
  profiles:
    active: development
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/webflux_practise_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true 

logging:
  level:
    io:
      r2dbc:
        postgresql:
          QUERY: DEBUG # for queries
          PARAM: DEBUG # for parameters

      
